(()=>{
  const PROD={url:'https://cayoyqwrmouxuttloemc.supabase.co',key:'sb_publishable_7RzACdnPmj_QiYSqzJRlfw_YaXyMws6'};
  const endpoint=PROD.url+'/functions/v1/lifecycle-nudge-preview';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const label=s=>String(s||'').replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
  function suppressionText(row){const reason=String(row?.suppression_reason||'');if(reason==='ANOTHER_MESSAGE_SELECTED'||reason==='LOWER_PRIORITY_SAME_RECIPIENT'){const winner=row?.selected_rule_key?label(row.selected_rule_key):'another message';return row?.selected_sequence?'Another message selected: '+row.selected_sequence+' · '+winner:'Another message selected for this recipient: '+winner}if(reason.startsWith('SUPERSEDED_BY_HIGHER_MILESTONE:'))return 'More advanced milestone selected: '+label(reason.split(':')[1]||'');return label(reason)}
  const client=window.supabase.createClient(PROD.url,PROD.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'dv-prod-nudge-preview'}});
  let token='',payload=null;
  async function auth(){const {data}=await client.auth.getSession();token=data.session?.access_token||'';return token}
  async function api(){await auth();if(!token)throw Object.assign(new Error('Sign in with a PROD Operator account to continue.'),{status:401});const r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+token,apikey:PROD.key},body:JSON.stringify({action:'preview'})});const out=await r.json().catch(()=>({}));if(!r.ok||!out.ok)throw Object.assign(new Error(out.error||'Preview request failed'),{status:r.status});return out}
  function rowsForFilter(rows){const q=document.getElementById('filter').value.trim().toLowerCase();if(!q)return rows;return rows.filter(r=>(String(r.recipient_name||'')+' '+String(r.driver_name||'')+' '+String(r.recipient_email||'')).toLowerCase().includes(q))}
  function recipientList(rows){rows=rowsForFilter(rows||[]);if(!rows.length)return '<p class="meta">None matching filter.</p>';return '<ul>'+rows.map(r=>'<li><strong>'+esc(r.recipient_name)+'</strong>'+(r.driver_name?' · '+esc(r.driver_name):'')+'<small>'+esc(r.recipient_email||'')+'</small>'+(r.suppression_reason?'<small>'+esc(suppressionText(r))+'</small>':'')+(r.state?'<small>'+esc((r.state.drive_count??0)+' drives · '+(r.state.usage_occasions??0)+' occasions · '+(r.state.total_minutes??0)+' minutes')+'</small>':'')+(r.message_preview?'<details class="recipient-preview"><summary>Resolved email</summary><pre>Subject: '+esc(r.message_preview.subject)+'\n\n'+esc(r.message_preview.heading)+'\n\n'+esc(r.message_preview.body)+'\n\nCTA: '+esc(r.message_preview.cta_label)+' → '+esc(r.message_preview.action_path)+'</pre></details>':'')+'</li>').join('')+'</ul>'}
  function card(g){const r=g.rule,s=g.selected||[],e=g.eligible_superseded||[],x=g.suppressed||[];return '<details class="nudge-card" '+(s.length?'open':'')+'><summary><span class="nudge-sequence-badge">'+esc(r.priority)+'</span><span class="nudge-card-title"><strong>'+esc(r.display_name)+'</strong><small>'+esc(r.description||'')+'</small></span><span class="nudge-counts"><span class="nudge-count selected">'+s.length+' selected</span><span class="nudge-count superseded">'+e.length+' superseded</span><span class="nudge-count suppressed">'+x.length+' suppressed</span></span></summary><div class="nudge-card-body"><div class="nudge-config readonly"><div><strong>Trigger</strong>'+esc(label(r.trigger_primitive))+'</div><div><strong>Post-send</strong>'+esc(label(r.post_send_behavior))+'</div><div><strong>Once only</strong>'+(r.once_only?'Yes':'No')+'</div></div><div class="recipient-columns"><div class="recipient-box"><h4>Selected</h4>'+recipientList(s)+'</div><div class="recipient-box"><h4>Eligible but superseded</h4>'+recipientList(e)+'</div><div class="recipient-box"><h4>Suppressed</h4>'+recipientList(x)+'</div></div></div></details>'}
  function render(){const groups=payload?.groups||[],q=document.getElementById('filter').value.trim().toLowerCase();const visible=groups.filter(g=>!q||[...(g.selected||[]),...(g.eligible_superseded||[]),...(g.suppressed||[])].some(r=>(String(r.recipient_name||'')+' '+String(r.driver_name||'')+' '+String(r.recipient_email||'')).toLowerCase().includes(q)));document.getElementById('summary').innerHTML='<span><strong>'+groups.reduce((n,g)=>n+(g.selected?.length||0),0)+'</strong> selected</span><span><strong>'+groups.reduce((n,g)=>n+(g.eligible_superseded?.length||0),0)+'</strong> superseded</span><span><strong>'+groups.reduce((n,g)=>n+(g.suppressed?.length||0),0)+'</strong> suppressed</span><span><strong>'+groups.length+'</strong> rules</span>';document.getElementById('groups').innerHTML=visible.map(card).join('')||'<p>No matching recipients.</p>';document.getElementById('limitations').textContent=(payload?.limitations||[]).join(' ')}
  async function load(){const err=document.getElementById('error');err.hidden=true;try{payload=await api();if(!payload.read_only||payload.environment!=='PROD')throw new Error('Safety check failed: endpoint did not identify as read-only PROD preview.');render();document.getElementById('dashboard').hidden=false;document.getElementById('signin').hidden=true;document.getElementById('access-status').textContent='PROD Operator access confirmed.'}catch(e){document.getElementById('access-status').textContent=e.message;if(e.status===401||e.status===403){document.getElementById('dashboard').hidden=true;document.getElementById('signin').hidden=false}else{err.textContent=e.message;err.hidden=false}}}
  document.getElementById('refresh').addEventListener('click',load);document.getElementById('filter').addEventListener('input',()=>payload&&render());
  document.getElementById('signin').addEventListener('submit',async e=>{e.preventDefault();const email=document.getElementById('signin-email').value.trim(),button=e.currentTarget.querySelector('button'),status=document.getElementById('signin-status');button.disabled=true;status.textContent='Sending PROD sign-in link…';try{const {error}=await client.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin+'/staging/nudge-live/',shouldCreateUser:false}});if(error)throw error;status.textContent='Check your email. The secure link should return to this PROD read-only preview.'}catch(err){status.textContent=err?.message||'Could not send sign-in link.';button.disabled=false}});
  auth().then(load);client.auth.onAuthStateChange((_e,s)=>{token=s?.access_token||'';if(s)load()});
})();