(()=>{const cfg=window.DV_APP_CONFIG||{},endpoint=String(window.DV_OPERATOR_ANALYTICS_ENDPOINT||''),checking=document.getElementById('families-checking'),denied=document.getElementById('families-denied'),app=document.getElementById('families-app'),errorEl=document.getElementById('families-error');let client=null,token='',data=null;
const STAGES=['REGISTERED','ONE_DRIVER','ONE_DRIVE','TWO_DRIVES','FIVE_DRIVES','MORE_THAN_5_DRIVES'],STAGE_LABEL={REGISTERED:'Registered',ONE_DRIVER:'1 driver',ONE_DRIVE:'1 drive',TWO_DRIVES:'2 drives',FIVE_DRIVES:'5 drives',MORE_THAN_5_DRIVES:'>5 drives'},params=new URLSearchParams(location.search);
let filter={q:'',exact:'ALL',reached:params.get('stage')==='driver'?'ONE_DRIVER':null,commercial:'ALL',status:'ALL',recency:'ALL',sort:'registered_desc',includeArchived:false};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>new Intl.NumberFormat('en-US').format(Number(v||0));
const date=v=>v?new Date(v).toLocaleDateString():'—',dateTime=v=>v?new Date(v).toLocaleString():'—';
const label=v=>String(v||'UNKNOWN').replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
const rank=stage=>Math.max(0,STAGES.indexOf(stage));
async function api(retried=false){let response=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`,apikey:cfg.publishableKey},body:JSON.stringify({action:'family_roster'})});if(response.status===401&&!retried){const {data:refreshed,error}=await client.auth.refreshSession();if(error||!refreshed.session?.access_token)throw new Error('Your operator session expired. Sign in again.');token=refreshed.session.access_token;return api(true)}const out=await response.json().catch(()=>({}));if(!response.ok||!out.ok){const e=new Error(out.error||`Family roster request failed (${response.status})`);e.status=response.status;throw e}return out}
function endpointLine(e){return `<div class="person-contact"><span>${esc(label(e.type))}</span><strong>${esc(e.value||e.normalized_value||'—')}</strong><small>${e.is_primary?'Primary · ':''}${e.is_verified?'Verified':'Unverified'} · ${esc(label(e.status))}</small></div>`}
function driverLine(d){return `<div class="person-driver"><span class="status-pill ${d.status==='ACTIVE'?'classified':'pending'}">${esc(label(d.status))}</span><strong>${esc(d.display_name||'Driver')}</strong><small>${num(d.eligible_drive_count)} eligible drive${d.eligible_drive_count===1?'':'s'} · ${esc(label(d.license_stage||'No license stage'))}</small></div>`}
function archivedDriverCard(d){return `<article class="family-person-card archived-driver-card"><div class="family-person-head"><div><strong>${esc(d.person_display_name||d.display_name||'Archived driver')}</strong><small>Historical driver · ${esc(label(d.membership_status||'inactive'))} membership</small></div><span class="status-pill pending">Archived</span></div><div class="person-drivers">${driverLine(d)}</div><details class="canonical-details"><summary>Canonical details</summary><code>Driver ${esc(d.id)}</code><code>Person ${esc(d.person_id)}</code></details></article>`}
function personCard(p){const access=(p.driver_access||[]).map(a=>`${esc(label(a.relationship||'guardian'))} → ${esc(String(a.driver_id).slice(0,8))}`).join(' · ');return `<article class="family-person-card"><div class="family-person-head"><div><strong>${esc(p.display_name)}</strong><small>${esc(label(p.role))}${p.is_license_holder?' · License Holder':''}${p.has_auth_access?' · Login access':''}</small></div>${p.is_license_holder?'<span class="status-pill classified">License Holder</span>':''}</div><div class="person-contacts">${(p.endpoints||[]).length?(p.endpoints||[]).map(endpointLine).join(''):'<p class="meta">No contact endpoint recorded.</p>'}</div>${(p.drivers||[]).length?`<div class="person-drivers">${p.drivers.map(driverLine).join('')}</div>`:''}${access?`<small class="person-access">Driver access: ${access}</small>`:''}<details class="canonical-details"><summary>Canonical details</summary><code>Person ${esc(p.id)}</code>${p.home_zip?`<code>ZIP ${esc(p.home_zip)}</code>`:''}</details></article>`}
function familyCard(f){const holder=f.license_holder?.display_name||'No License Holder',inactive=f.status!=='ACTIVE',archived=filter.includeArchived?(f.archived_drivers||[]):[];return `<details class="family-roster-card" data-family-id="${esc(f.id)}"><summary><span class="family-summary-main"><strong>${esc(holder)}</strong><small>${esc(f.family_code||String(f.id).slice(0,8))} · registered ${esc(date(f.registered_at))}</small></span><span><small>Activation</small><strong>${esc(STAGE_LABEL[f.activation_stage]||label(f.activation_stage))}</strong></span><span><small>Drivers</small><strong>${num(f.driver_count)}</strong></span><span><small>Eligible drives</small><strong>${num(f.eligible_drive_count)}</strong></span><span><small>Commercial</small><strong>${esc(label(f.commercial_state))}</strong></span><span><small>Latest activity</small><strong>${esc(f.latest_activity_at?date(f.latest_activity_at):'—')}</strong></span>${inactive?`<span class="status-pill pending">${esc(label(f.status))}</span>`:''}</summary><div class="family-detail"><div class="family-detail-meta"><span><b>License Holder:</b> ${esc(holder)}</span><span><b>Latest drive:</b> ${esc(f.latest_drive_date||'—')}</span><span><b>Last activity:</b> ${esc(dateTime(f.latest_activity_at))}</span><span><b>Entitlement:</b> ${esc(label(f.entitlement?.entitlement_basis||'None'))}</span>${filter.includeArchived?`<span><b>Archived drivers:</b> ${num(f.archived_driver_count||archived.length)}</span>`:''}</div><div class="family-people-grid">${(f.people||[]).map(personCard).join('')||'<p>No active family members recorded.</p>'}${archived.map(archivedDriverCard).join('')}</div><details class="canonical-details"><summary>Family canonical ID</summary><code>${esc(f.id)}</code></details></div></details>`}
function renderFunnel(){const max=Math.max(1,...(data.funnel||[]).map(x=>Number(x.count||0))),el=document.getElementById('activation-funnel');el.innerHTML=(data.funnel||[]).map((x,i)=>{const w=Math.max(44,Number(x.count||0)/max*100),pressed=filter.reached===x.key;return `<button type="button" class="activation-funnel-stage ${pressed?'active':''}" data-reached="${esc(x.key)}" aria-pressed="${pressed}" style="--funnel-width:${w}%"><span>${esc(x.label)}</span><strong>${num(x.count)}</strong><small>${i?(x.conversion_from_previous_pct==null?'—':Number(x.conversion_from_previous_pct).toFixed(1)+'% from prior'):'Active families'}</small></button>`}).join('');document.getElementById('stalled-filters').innerHTML=STAGES.map(s=>`<button type="button" class="basis-button ${filter.exact===s?'active':''}" data-stalled="${s}" aria-pressed="${filter.exact===s}">${esc(STAGE_LABEL[s])}</button>`).join('')}
function renderCommercial(){const el=document.getElementById('commercial-summary');el.innerHTML=(data.commercial||[]).map(x=>`<button type="button" class="commercial-state ${filter.commercial===x.state?'active':''}" data-commercial="${esc(x.state)}" aria-pressed="${filter.commercial===x.state}"><span>${esc(label(x.state))}</span><strong>${num(x.count)}</strong></button>`).join('');const sel=document.getElementById('family-commercial'),states=(data.commercial||[]).map(x=>x.state);sel.innerHTML='<option value="ALL">All commercial states</option>'+states.map(s=>`<option value="${esc(s)}">${esc(label(s))}</option>`).join('');sel.value=filter.commercial}
function searchHaystack(f){const archived=filter.includeArchived?(f.archived_drivers||[]).flatMap(d=>[d.person_display_name,d.display_name,d.home_city,d.home_state,d.license_stage]):[];return [f.family_code,f.status,f.commercial_state,f.license_holder?.display_name,...(f.people||[]).flatMap(p=>[p.display_name,p.given_name,p.family_name,p.home_zip,...(p.endpoints||[]).flatMap(e=>[e.value,e.normalized_value]),...(p.drivers||[]).flatMap(d=>[d.display_name,d.home_city,d.home_state,d.license_stage])]),...archived].filter(Boolean).join(' ').toLowerCase()}
function filteredFamilies(){const now=Date.now(),q=filter.q.trim().toLowerCase();let rows=(data.families||[]).filter(f=>{if(q&&!searchHaystack(f).includes(q))return false;if(filter.exact!=='ALL'&&f.activation_stage!==filter.exact)return false;if(filter.reached&&rank(f.activation_stage)<rank(filter.reached))return false;if(filter.commercial!=='ALL'&&f.commercial_state!==filter.commercial)return false;if(filter.status==='ACTIVE'&&f.status!=='ACTIVE')return false;if(filter.status==='INACTIVE'&&f.status==='ACTIVE')return false;if(filter.recency!=='ALL'&&(now-new Date(f.registered_at).getTime())>Number(filter.recency)*86400000)return false;return true});rows=rows.slice().sort((a,b)=>filter.sort==='activity_desc'?new Date(b.latest_activity_at||0)-new Date(a.latest_activity_at||0):filter.sort==='drives_desc'?b.eligible_drive_count-a.eligible_drive_count:filter.sort==='name_asc'?String(a.license_holder?.display_name||a.family_code||'').localeCompare(String(b.license_holder?.display_name||b.family_code||'')):new Date(b.registered_at)-new Date(a.registered_at));return rows}
function renderRoster(){const rows=filteredFamilies(),total=(data.families||[]).length;document.getElementById('families-count').textContent=`Showing ${num(rows.length)} of ${num(total)} family units`;document.getElementById('families-updated').textContent=`Updated ${new Date(data.generated_at).toLocaleString()}`;document.getElementById('family-roster').innerHTML=rows.map(familyCard).join('');document.getElementById('family-empty').hidden=rows.length>0;const note=document.getElementById('active-family-filter');const bits=[];if(filter.reached)bits.push(`Reached ${STAGE_LABEL[filter.reached]}`);if(filter.exact!=='ALL')bits.push(`Stalled at ${STAGE_LABEL[filter.exact]}`);note.hidden=!bits.length;note.textContent=bits.length?`Activation filter: ${bits.join(' · ')}`:''}
function syncControls(){document.getElementById('family-search').value=filter.q;document.getElementById('family-stage').value=filter.exact;document.getElementById('family-commercial').value=filter.commercial;document.getElementById('family-status').value=filter.status;document.getElementById('family-recency').value=filter.recency;document.getElementById('family-sort').value=filter.sort;document.getElementById('include-archived-drivers').checked=filter.includeArchived}
function render(){renderFunnel();renderCommercial();syncControls();renderRoster();errorEl.hidden=true}
async function load(){errorEl.hidden=true;try{data=await api();render()}catch(e){errorEl.textContent=e.message||String(e);errorEl.hidden=false;throw e}}
document.getElementById('activation-funnel').addEventListener('click',e=>{const b=e.target.closest('[data-reached]');if(!b)return;filter.reached=filter.reached===b.dataset.reached?null:b.dataset.reached;render()});
document.getElementById('stalled-filters').addEventListener('click',e=>{const b=e.target.closest('[data-stalled]');if(!b)return;filter.exact=filter.exact===b.dataset.stalled?'ALL':b.dataset.stalled;render()});
document.getElementById('commercial-summary').addEventListener('click',e=>{const b=e.target.closest('[data-commercial]');if(!b)return;filter.commercial=filter.commercial===b.dataset.commercial?'ALL':b.dataset.commercial;render()});
document.getElementById('family-search').addEventListener('input',e=>{filter.q=e.target.value;renderRoster()});
document.getElementById('include-archived-drivers').addEventListener('change',e=>{filter.includeArchived=Boolean(e.target.checked);render()});
for(const [id,key] of [['family-stage','exact'],['family-commercial','commercial'],['family-status','status'],['family-recency','recency'],['family-sort','sort']])document.getElementById(id).addEventListener('change',e=>{filter[key]=e.target.value;render()});
document.getElementById('clear-family-filters').addEventListener('click',()=>{filter={q:'',exact:'ALL',reached:null,commercial:'ALL',status:'ALL',recency:'ALL',sort:'registered_desc',includeArchived:false};history.replaceState(null,'',location.pathname);render()});
document.getElementById('refresh-families').addEventListener('click',()=>load().catch(()=>{}));
(async()=>{try{if(!window.supabase||!cfg.supabaseUrl||!cfg.publishableKey||!endpoint)throw new Error('Drive Venture operator configuration is unavailable.');client=window.supabase.createClient(cfg.supabaseUrl,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true}});client.auth.onAuthStateChange((_event,session)=>{token=session?.access_token||''});const {data:{session}}=await client.auth.getSession();if(!session?.access_token)throw Object.assign(new Error('Sign in with an operator account to continue.'),{status:401});token=session.access_token;data=await api();render();checking.hidden=true;app.hidden=false}catch(e){checking.hidden=true;if(e.status===401||e.status===403){denied.hidden=false;document.getElementById('families-denied-detail').textContent=e.message||'Operator access required.'}else{app.hidden=false;errorEl.textContent=`The family roster could not load: ${e.message||String(e)}`;errorEl.hidden=false}}})()})();