(() => {
  const cfg=window.DV_APP_CONFIG||{}, endpoint=String(window.DV_OPERATOR_FEEDBACK_ENDPOINT||'').trim();
  const msg=document.getElementById('operator-message'), inbox=document.getElementById('feedback-inbox'), workbench=document.getElementById('feedback-workbench');
  let token='', selected=null, feedback=[];
  function status(t,e=false){msg.textContent=t||'';msg.classList.toggle('error',e)}
  function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  async function api(action,data={}){if(!token)throw new Error('Sign in through Drive Venture before using operator tools.');const r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+token},body:JSON.stringify({action,...data})});const out=await r.json().catch(()=>({}));if(!r.ok||out.ok!==true)throw new Error(out.error||'Operator request failed');return out}
  function fd(form){return Object.fromEntries(new FormData(form).entries())}
  async function init(){if(!window.supabase||!cfg.supabaseUrl||!cfg.publishableKey)throw new Error('Drive Venture sign-in configuration unavailable.');const c=window.supabase.createClient(cfg.supabaseUrl,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true}});const {data:{session}}=await c.auth.getSession();if(!session?.access_token)throw new Error('Sign in through Drive Venture first.');token=session.access_token;await load()}
  async function load(){status('');const out=await api('list');feedback=out.feedback||[];const links=out.links||[];const byCode=new Map();for(const l of links){if(!byCode.has(l.feedback_code))byCode.set(l.feedback_code,[]);byCode.get(l.feedback_code).push(l)};inbox.innerHTML=feedback.length?feedback.map(f=>`<button type="button" class="button button-secondary feedback-pick" data-code="${esc(f.feedback_code)}" style="display:block;width:100%;text-align:left;margin:.5rem 0"><strong>${esc(f.feedback_code)}</strong> · ${esc(f.status)} · ${esc(f.disposition_category||'unclassified')}<br><span>${esc(f.category)} / ${esc(f.area)} — ${esc(String(f.message).slice(0,140))}</span><br><small>${esc(f.created_at)}${f.follow_up_requested?' · response requested':''}${f.updates_opt_in?' · updates opted in':''}${(byCode.get(f.feedback_code)||[]).length?' · '+(byCode.get(f.feedback_code)||[]).map(x=>x.backlog_code).join(', '):''}</small></button>`).join(''):'<p>No feedback yet.</p>';for(const b of inbox.querySelectorAll('.feedback-pick'))b.addEventListener('click',()=>select(b.dataset.code))}
  function select(code){selected=feedback.find(f=>f.feedback_code===code);if(!selected)return;document.getElementById('selected-code').textContent=selected.feedback_code;document.getElementById('selected-message').textContent=selected.message;document.getElementById('selected-meta').textContent=`${selected.category} / ${selected.area} · ${selected.status} · project ${selected.project_state||''} · revision ${selected.code_revision||'not supplied'}${selected.follow_up_requested?' · personal response required':''}${selected.updates_opt_in?' · backlog updates enabled':''}`;const sel=document.querySelector('#classify-form [name="disposition_category"]');if(selected.disposition_category)sel.value=selected.disposition_category;document.getElementById('ack-form').hidden=!selected.follow_up_requested;workbench.hidden=false;workbench.scrollIntoView({behavior:'smooth',block:'start'})}
  async function run(form,action,extra={}){if(!selected&&action!=='record_backlog_closed')throw new Error('Select feedback first.');const data=fd(form);status('Working…');const out=await api(action,{...(selected?{feedback_code:selected.feedback_code}:{}),...data,...extra});status('Saved.');await load();if(selected)select(selected.feedback_code);return out}
  document.getElementById('refresh-feedback').addEventListener('click',()=>load().catch(e=>status(e.message,true)));
  document.getElementById('operator-entry').addEventListener('submit',async e=>{e.preventDefault();try{const d=fd(e.currentTarget);d.follow_up_requested=new FormData(e.currentTarget).get('follow_up_requested')==='on';d.updates_opt_in=new FormData(e.currentTarget).get('updates_opt_in')==='on';d.code_revision=String(window.DV_CODE_REVISION||'');status('Recording…');const out=await api('log_on_behalf',d);e.currentTarget.reset();status(`Recorded ${out.feedback_code}.`);await load()}catch(x){status(x.message,true)}});
  document.getElementById('classify-form').addEventListener('submit',e=>{e.preventDefault();run(e.currentTarget,'read_and_classify').catch(x=>status(x.message,true))});
  document.getElementById('ack-form').addEventListener('submit',e=>{e.preventDefault();run(e.currentTarget,'acknowledge').catch(x=>status(x.message,true))});
  document.getElementById('link-form').addEventListener('submit',e=>{e.preventDefault();run(e.currentTarget,'link_backlog').catch(x=>status(x.message,true))});
  document.getElementById('disposition-form').addEventListener('submit',e=>{e.preventDefault();run(e.currentTarget,'disposition').catch(x=>status(x.message,true))});
  document.getElementById('close-backlog-form').addEventListener('submit',async e=>{e.preventDefault();try{status('Recording closure…');const out=await api('record_backlog_closed',fd(e.currentTarget));status(`Closed ${out.backlog_code} for ${out.linked_feedback_count} linked feedback item(s).`);e.currentTarget.reset();await load()}catch(x){status(x.message,true)}});
  document.getElementById('show-attachments').addEventListener('click',async()=>{try{const out=await api('attachments',{feedback_code:selected.feedback_code});document.getElementById('attachment-list').innerHTML=(out.attachments||[]).length?(out.attachments||[]).map(a=>`<p><a href="${esc(a.signed_url)}" target="_blank" rel="noopener">${esc(a.original_filename||'Screenshot')}</a> · ${Math.round(a.size_bytes/1024)} KB</p>`).join(''):'<p>No screenshots.</p>'}catch(x){status(x.message,true)}});
  init().catch(e=>status(e.message,true));
})();
