(()=>{const cfg=window.DV_APP_CONFIG||{},endpoint=String(window.DV_OPERATOR_CLASSIFICATION_ENDPOINT||''),checking=document.getElementById('classification-checking'),denied=document.getElementById('classification-denied'),app=document.getElementById('classification-app'),errorEl=document.getElementById('classification-error');let client=null,token='',data=null,filter='all';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=v=>new Intl.NumberFormat('en-US').format(Number(v||0));
const label=v=>String(v||'UNKNOWN').replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
const done=v=>['CLASSIFIED','NOT_REQUIRED'].includes(String(v||''));
async function api(retried=false){let response=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`,apikey:cfg.publishableKey},body:'{}'});if(response.status===401&&!retried){const {data:refreshed,error}=await client.auth.refreshSession();if(error||!refreshed.session?.access_token)throw new Error('Your operator session expired. Sign in again.');token=refreshed.session.access_token;return api(true)}const out=await response.json().catch(()=>({}));if(!response.ok||!out.ok){const e=new Error(out.error||`Classification request failed (${response.status})`);e.status=response.status;throw e}return out}
function stat(name,value){return `<article class="classification-stat"><span>${esc(name)}</span><strong>${number(value)}</strong></article>`}
function pill(name,value){return `<span class="status-pill ${done(value)?'classified':'pending'}">${esc(name)}: ${esc(label(value))}</span>`}
function matches(item){const night=String(item.night_classification_status||''),weather=String(item.weather_classification_status||'');if(filter==='night')return !done(night);if(filter==='weather')return !done(weather);if(filter==='location')return night==='LOCATION_PENDING'||weather==='LOCATION_PENDING';if(filter==='lookup')return night==='LOOKUP_PENDING'||weather==='LOOKUP_PENDING';return true}
function render(){const s=data.summary,items=(data.items||[]).filter(matches);document.getElementById('classification-summary').innerHTML=[stat('Total pending drives',s.total),stat('Night pending',s.night),stat('Weather pending',s.weather),stat('Lookup pending',s.lookup_pending)].join('');document.getElementById('classification-count').textContent=`Showing ${number(items.length)} of ${number(s.total)} drives`;document.getElementById('classification-updated').textContent=`Updated ${new Date(data.generated_at).toLocaleString()}`;document.querySelectorAll('[data-filter]').forEach(b=>{const active=b.dataset.filter===filter;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});const rows=document.getElementById('classification-rows'),empty=document.getElementById('classification-empty');rows.innerHTML=items.map(item=>`<tr><td><strong>${esc(item.driver_name)}</strong><small>${esc(item.drive_date)} · ${esc(String(item.start_time||'').slice(0,5))}–${esc(String(item.end_time||'').slice(0,5))} · ${number(item.duration_minutes)} min</small><small>${esc(item.destination||'No destination recorded')}</small></td><td>${esc(label(item.source))}</td><td>${pill('Night',item.night_classification_status)}${pill('Weather',item.weather_classification_status)}</td><td>${esc(item.classification_zip||'No ZIP')}<small>${esc(label(item.classification_basis||'No location basis'))}</small></td></tr>`).join('');empty.hidden=items.length>0;errorEl.hidden=true}
async function load(){errorEl.hidden=true;try{data=await api();render()}catch(e){errorEl.textContent=e.message||String(e);errorEl.hidden=false;throw e}}
document.getElementById('classification-filters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;filter=b.dataset.filter;render()});document.getElementById('refresh-classification').addEventListener('click',()=>load().catch(()=>{}));
(async()=>{try{if(!window.supabase||!cfg.supabaseUrl||!cfg.publishableKey||!endpoint)throw new Error('Drive Venture operator configuration is unavailable.');client=window.supabase.createClient(cfg.supabaseUrl,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true}});client.auth.onAuthStateChange((_event,session)=>{token=session?.access_token||''});const {data:{session}}=await client.auth.getSession();if(!session?.access_token)throw Object.assign(new Error('Sign in with an operator account to continue.'),{status:401});token=session.access_token;data=await api();render();checking.hidden=true;app.hidden=false}catch(e){checking.hidden=true;denied.hidden=false;document.getElementById('classification-denied-detail').textContent=e.message||'Operator access required.'}})()})();
