(()=>{const cfg=window.DV_APP_CONFIG||{},endpoint=String(window.DV_OPERATOR_ANALYTICS_ENDPOINT||''),checking=document.getElementById('operator-checking'),denied=document.getElementById('operator-denied'),app=document.getElementById('operator-dashboard'),errorEl=document.getElementById('dashboard-error');let client=null,token='',data=null,range='30';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=v=>new Intl.NumberFormat('en-US').format(Number(v||0));
const time=m=>{const n=Math.max(0,Math.round(Number(m||0))),h=Math.floor(n/60),r=n%60;return h?`${number(h)}h ${r}m`:`${r}m`};
const signed=v=>`${Number(v)>=0?'+':''}${number(v)}`;
async function api(retried=false){let response=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({range})});if(response.status===401&&!retried){const {data:refreshed,error}=await client.auth.refreshSession();if(error||!refreshed.session?.access_token)throw new Error('Your operator session expired. Sign in again.');token=refreshed.session.access_token;return api(true)}const out=await response.json().catch(()=>({}));if(!response.ok||!out.ok){const e=new Error(out.error||`Analytics request failed (${response.status})`);e.status=response.status;throw e}return out}
function compare(metric,unit='records'){if(metric.previous===null)return `${number(metric.current)} ${unit} in the selected all-time range`;const days=data.range.key;return `${number(metric.current)} ${unit} in this ${days}-day period · ${signed(metric.change)} versus the previous ${days} days`}
function card(label,metric,format=number,unit='new'){return `<article class="operator-kpi"><p>${esc(label)}</p><strong>${format(metric.value)}</strong><small>${esc(compare(metric,unit))}</small></article>`}
function renderSummary(){const s=data.summary;document.getElementById('kpis').innerHTML=[card('Active families',s.active_families),card('Registered people',s.registered_people),card('Active drivers',s.active_drivers),card('Eligible drives',s.eligible_drives,number,'drives'),card('Logged time',s.logged_minutes,time,'minutes'),card('Pending feedback',s.pending_feedback,number,'received'),card('Active product themes',s.active_themes,number,'signals'),`<article class="operator-kpi"><p>Active backlog</p><strong>${number(s.active_backlog.value)}</strong><small>${number(s.active_backlog.blocked)} blocked · ${number(s.active_backlog.created.current)} created and ${number(s.active_backlog.closed.current)} closed in this period</small></article>`].join('')}
const METRICS={drives:['Drives','drives',number],minutes:['Logged time','minutes',time],registrations:['Registrations','registrations',number],active_drivers:['Active drivers','active drivers',number],feedback_received:['Feedback received','feedback received',number],feedback_resolved:['Feedback resolved','feedback resolved',number],signals_observed:['Product signals','signals observed',number],backlog_created:['Backlog created','items created',number],backlog_closed:['Backlog closed','items closed',number]};
function renderChart(){const key=document.getElementById('trend-metric').value,[label,unit,fmt]=METRICS[key],rows=data.trends,max=Math.max(1,...rows.map(x=>Number(x[key]||0))),width=900,height=260,pad=34,gap=Math.max(1,Math.min(6,620/Math.max(rows.length,1))),bar=Math.max(2,(width-pad*2)/Math.max(rows.length,1)-gap),marks=rows.map((row,i)=>{const value=Number(row[key]||0),h=(height-pad*2)*(value/max),x=pad+i*((width-pad*2)/rows.length),y=height-pad-h;return `<rect x="${x.toFixed(2)}" y="${y.toFixed(2)}" width="${bar.toFixed(2)}" height="${h.toFixed(2)}" rx="2"><title>${esc(row.date)}: ${esc(fmt(value))} ${esc(unit)}</title></rect>`}).join(''),first=rows[0]?.date||'',last=rows.at(-1)?.date||'';document.getElementById('trend-title').textContent=label;document.getElementById('trend-chart').innerHTML=`<title>${esc(label)} from ${esc(first)} through ${esc(last)}</title><line x1="${pad}" y1="${height-pad}" x2="${width-pad}" y2="${height-pad}"></line>${marks}<text x="${pad}" y="${height-8}">${esc(first)}</text><text x="${width-pad}" y="${height-8}" text-anchor="end">${esc(last)}</text><text x="${pad}" y="20">Max ${esc(fmt(max))}</text>`;document.getElementById('trend-table').innerHTML=`<thead><tr><th>Date</th><th>${esc(label)}</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.date)}</td><td>${esc(fmt(r[key]))}</td></tr>`).join('')}</tbody>`}
function renderChannels(){const rows=data.channels,total=Math.max(1,...rows.map(x=>x.drives));document.getElementById('channels').innerHTML=rows.length?rows.map(x=>`<article class="channel-row"><div><strong>${esc(x.label)}</strong><small>${number(x.drives)} drives · ${time(x.minutes)}</small></div><span><i style="width:${Math.max(3,x.drives/total*100)}%"></i></span></article>`).join(''):'<p>No eligible drives occurred in this period.</p>'}
function attention(label,value,href,detail=''){const count=Array.isArray(value)?value.length:Number(value||0);return `<a class="attention-row ${count?'needs-attention':'clear'}" href="${href}"><span>${esc(label)}</span><strong>${number(count)}</strong>${detail?`<small>${esc(detail)}</small>`:''}</a>`}
function renderAttention(){const f=data.feedback_health,a=data.attention,blocked=(a.blocked_high_priority||[]);document.getElementById('attention').innerHTML=[attention('Unread feedback',f.unread,'/operator/feedback/'),attention('Awaiting disposition',f.awaiting_disposition,'/operator/feedback/'),attention('Follow-up or linked work outstanding',f.followup_or_linked_work,'/operator/feedback/'),attention('Themes with new evidence',a.themes_with_new_evidence,'/operator/themes/',(a.themes_with_new_evidence||[]).join(', ')),attention('Onboarding exceptions',a.onboarding_exceptions,'/operator/'),attention('Classification backlog',a.classification_backlog,'/operator/'),attention('Blocked P0/P1 backlog',blocked,'/operator/backlog/',blocked.map(x=>x.code).join(', '))].join('')}
function render(){document.querySelectorAll('[data-range]').forEach(b=>{b.classList.toggle('active',b.dataset.range===range);b.setAttribute('aria-pressed',String(b.dataset.range===range))});document.getElementById('window-label').textContent=`${data.range.start} through ${data.range.end} · ${data.timezone}`;document.getElementById('generated-at').textContent=`Updated ${new Date(data.generated_at).toLocaleString()}`;renderSummary();renderChart();renderChannels();renderAttention();errorEl.hidden=true}
async function load(){errorEl.hidden=true;try{data=await api();render()}catch(e){errorEl.textContent=e.message||String(e);errorEl.hidden=false;throw e}}
document.querySelectorAll('[data-range]').forEach(b=>b.addEventListener('click',async()=>{range=b.dataset.range;await load().catch(()=>{})}));document.getElementById('trend-metric').addEventListener('change',renderChart);document.getElementById('refresh-dashboard').addEventListener('click',()=>load().catch(()=>{}));
(async()=>{try{if(!window.supabase||!cfg.supabaseUrl||!cfg.publishableKey||!endpoint)throw new Error('Drive Venture operator configuration is unavailable.');client=window.supabase.createClient(cfg.supabaseUrl,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true}});client.auth.onAuthStateChange((_event,session)=>{token=session?.access_token||''});const {data:{session}}=await client.auth.getSession();if(!session?.access_token)throw Object.assign(new Error('Sign in with an operator account to continue.'),{status:401});token=session.access_token;data=await api();render();checking.hidden=true;app.hidden=false}catch(e){checking.hidden=true;denied.hidden=false;document.getElementById('operator-denied-detail').textContent=e.message||'Operator access required.'}})()})();
